# Generated by Django 4.2.2 on 2023-06-06 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_placeid_geo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geo',
            old_name='pieceid',
            new_name='id',
        ),
    ]
