# Generated by Django 4.2.2 on 2023-06-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_pieceid_geo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geo',
            name='id',
        ),
        migrations.AddField(
            model_name='geo',
            name='placeid',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
