# Generated by Django 4.2.2 on 2023-06-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_geo_id_geo_placeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geo',
            name='placeid',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
