# Generated by Django 4.2.1 on 2023-05-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('placeid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('latitude', models.FloatField(max_length=10)),
                ('longitude', models.FloatField(max_length=10)),
            ],
        ),
    ]
